import type { ProofPhoto, ProofSite } from "./types";

/**
 * Cedar Bend Guide: the community guide proof site (site-building programme B4). A fictional
 * mountain town in the San Juans, written as a client would fill in the onboarding package:
 * a directory of nineteen places with verified details, the autumn's events, six articles,
 * the brand and the starter pages' text. The photographs are Carol M. Highsmith's of real
 * Colorado towns and valleys (Ouray, Ridgway, Telluride, Crested Butte, Steamboat Springs and
 * others), public domain through the Library of Congress; none shows a business named on
 * these pages, and every place, person, address and phone number here is invented.
 */

const week = (open: string, close: string, except: Partial<Record<"mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun", string>> = {}): Record<string, string> => {
  const hours: Record<string, string> = {};
  for (const d of ["mon", "tue", "wed", "thu", "fri", "sat", "sun"] as const) hours[`hours_${d}`] = except[d] ?? `${open}-${close}`;
  return hours;
};

const photo = (file: string, loc: string, item: string, locTitle: string, title: string, alt: string): ProofPhoto => ({ file, loc, sourceUrl: `https://www.loc.gov/item/${item}/`, locTitle, title, alt });

const photos: ProofPhoto[] = [
  photo("main-street.jpg", "33500:33500", "2015633515", "Elk Avenue, the main street of Crested Butte, a town heavily populated during ski season located high in the Rocky Mountains in Gunnison County, Colorado", "Main Street in summer", "A small town's main street on a summer day: two-storey false-front shops on both sides, a cyclist in the road and forested mountains at the end of the street"),
  photo("downtown.jpg", "32300:32363", "2015632378", "[Downtown Ouray, Colorado]", "Downtown under the peaks", "Storefronts along a main street with a wall of grey mountains rising straight behind them"),
  photo("main-street-block.jpg", "32300:32307", "2015632322", "A block of Main Street in Ouray, Colorado, an old mining community high in the San Juan Mountains of southwestern Colorado", "A block of Main Street", "A block of brick and timber storefronts under snow-streaked peaks"),
  photo("valley-view.jpg", "37700:37752", "2017687644", "View of Pleasant Valley and distant mountains around Ridgway, Colorado", "The valley from the mesa", "A wide green valley under scattered clouds, with a snow-capped range along the horizon"),
  photo("alta-lake.jpg", "37700:37749", "2017687641", "Rocky Mountain reflection in one of the string of Alta Lakes outside Telluride, Colorado", "Alta Lake at noon", "A snow-capped ridge and dark forest reflected in a perfectly still alpine lake"),
  photo("trout-lake.jpg", "35100:35102", "2017685585", "Fall view of Trout Lake, near Telluride in San Miguel, Colorado", "Trout Lake in October", "A lake in a high valley in autumn, yellow aspens on the slopes and a bank of white clouds above the peaks"),
  photo("sunset-valley.jpg", "34500:34594", "2017685077", "Spectacular Rocky Mountain valley outside Telluride, Colorado", "Dusk over the valley", "Pink clouds over a mountain valley at dusk, with a pond reflecting the sky"),
  photo("fall-valley.jpg", "35100:35137", "2017685620", "Fall splendor in a valley outside Telluride, Colorado", "The valley in colour", "A valley in full autumn colour: yellow aspens, dark spruce and a creek under a bright sky"),
  photo("aspen-trunks.jpg", "33700:33779", "2015633795", "Aspen trees along the high dirt road leading to Crested Butte, Colorado, from the distant Crystal River Valley", "Aspens along the high road", "White aspen trunks standing close together, green leaves above"),
  photo("peaks.jpg", "37800:37867", "2017687759", "Some of the high Rocky Mountains that surround Telluride, Colorado", "The peaks from Sunset Ridge", "A row of snow-streaked peaks above a green ridge under piled white clouds"),
  photo("meadows.jpg", "33700:33703", "2015633719", "Meadows and Rocky Mountain foothills outside the town of Steamboat Springs, Colorado", "The lower meadows", "Tall summer grass in a meadow, forested hills and a blue sky beyond"),
  photo("winter-fence.jpg", "36300:36312", "2017686795", "Winter scene in mountainous Ouray County, Colorado, near Telluride and the town of Ouray", "Winter on the valley road", "A snow-covered field with a wooden fence and a line of white peaks under a cold sky"),
  photo("alpenglow.jpg", "35800:35833", "2017686316", "Mountain-sunset view from Telluride, once a mining boomtown and now a popular skiing destination in Colorado", "Alpenglow", "The last light of the day on a mountain wall above a shadowed, forested valley"),
  photo("elk.jpg", "37700:37789", "2017687681", "Some elk cows graze while others keep a watchful eye on their recently born calves near the San Miguel River, below Telluride in San Miguel County, Colorado", "Elk in the lower meadows", "Elk cows grazing in a meadow at the edge of aspen woods, a few lying in the grass"),
  photo("lupines.jpg", "37800:37870", "2017687762", "Purple lupines -- a sure sign of Spring in Colorado -- pop up in Ridgway, Colorado. Lupine plants are legumes, with small, edible, pea-type seed pods. Lupine, sometime spelled \"lupin,\" is pronounced \"LOOP-in\"", "Lupines on the mesa", "Purple lupines blooming among green leaves on a hillside"),
  photo("cottonwoods.jpg", "35000:35018", "2017685501", "Cottonwoods are ablaze with fall colors along the Colorado River, near Parshall, Colorado", "The river in October", "A shallow river between banks of golden cottonwoods in autumn"),
  photo("aspens-cliff.jpg", "34500:34562", "2017685045", "Fall aspens in San Juan County, Colorado", "First colour on the ridge", "A stand of golden aspens on top of a rock outcrop against a deep blue sky"),
  photo("coffee-cart.jpg", "37100:37152", "2017687310", "Coffee kiosk in a small trailer on a day when heavy snow covers the main street of Telluride, Colorado", "The coffee cart in winter", "A small coffee trailer parked in deep snow beside a dark building, its service window open"),
  photo("mercantile.jpg", "34100:34149", "2015634165", "The general store in Aladdin, Wyoming", "The Mercantile", "A two-storey red general store with a covered porch and fuel pumps out front, pines behind"),
  photo("bookshop.jpg", "32300:32364", "2015632379", "[Buildings in Ouray, Colorado]", "The corner of Main and Sixth", "A red brick corner building with tall ground-floor windows below a mountainside"),
  photo("bike-shop.jpg", "33400:33495", "2015633510", "Lots of bicycles, a common sight in health-conscious Colorado, lie outside a cottage in Crested Butte, a town heavily populated during ski season located high in the Rocky Mountains in Gunnison County, Colorado", "Spoke & Saddle", "A pale blue wooden cottage with several bicycles leaning against its porch"),
  photo("fly-shop.jpg", "33500:33511", "2015633526", "The Crested Butte Angler shop in Crested Butte, a town heavily populated during ski season located high in the Rocky Mountains in Gunnison County, Colorado", "The fly shop", "A narrow blue Victorian house with white trim and a shop sign by the porch, a spruce beside it"),
  photo("hot-springs-pool.jpg", "32300:32390", "2015632405", "[Ouray Hot Springs, Pool. Ouray, Colorado]", "The hot springs pool", "A large outdoor hot springs pool with swimmers, a water slide and a mountainside behind"),
  photo("inn-pool.jpg", "32300:32316", "2015632331", "Pool at the Wiesbaden Hot Springs Hotel, a small spa in Ouray, Colorado, an old mining community high in the San Juan Mountains of southwestern Colorado. A number of hot springs bubble to the surface in and near Ouray", "The inn's soaking pool", "A small outdoor pool beside a timber lodge with a wall of windows, trees and peaks behind"),
  photo("cabins.jpg", "36200:36237", "2017686720", "Cabins in the snow west of Ridgway in Ouray County, Colorado", "Timberline Cabins in January", "Wooden cabins in deep snow with a bare ridge behind them"),
  photo("library.jpg", "32300:32368", "2015632383", "[Walsh Library, Ouray, Colorado]", "The library", "A stone civic building with a clock tower and a flag, cars parked in front and a cliff behind"),
  photo("park-pavilion.jpg", "32200:32214", "2015632229", "A stone building at Willow Creek Park, developed in 1933 as Colorado's first Works Progress Administration (WPA) depression-era work project in Lamar, Colorado", "The park pavilion", "A stone pavilion under tall cottonwoods in a green park"),
  photo("mill-museum.jpg", "34800:34825", "2017685308", "The old Mayflower Gold Mill above Silverton, Colorado. The mill, which today (in 2015) offers seasonal tours, began to take shape in the summer of 1925 as the dream of Charles A. Chase, who was a successful mine manager at the Liberty Bell Mine near Telluride, Colorado", "The Old Mill", "An old timber mill on a slope of golden aspens below a grey mountain"),
  photo("depot.jpg", "32400:32434", "2015632449", "The 1891 Rio Grande Southern Depot, with a new roof, in the town of Ridgway, which was named for Robert Ridgway, the railroad's superintendent. Ridgway, Colorado", "The depot", "A restored railway depot with a steep red roof and gabled dormers"),
  photo("gallery.jpg", "33500:33512", "2015633527", "A former bank and drug store turned art gallery in Crested Butte, a town heavily populated during ski season located high in the Rocky Mountains in Gunnison County, Colorado", "Bend Gallery", "A red false-front building with large display windows and a bench out front"),
  photo("carvers-yard.jpg", "36400:36426", "2017686909", "Woodcarvings for sale outside a shop in Aspen, once a mining boomtown that became a prominent ski resort and hangout of prominent Hollywood stars, in Pitkin County, Colorado", "Carver's Yard", "Carved wooden bears, eagles and figures displayed outside a shop's windows"),
  photo("church-hall.jpg", "33700:33753", "2015633769", "Marble Community Church in in the tiny mountain town Marble, Colorado, in the Crystal River Valley of Colorado", "The community hall", "A small white wooden church with a square tower among tall pines"),
  photo("falls-trail.jpg", "32300:32349", "2015632364", "[Bear Creek Falls in the San Juan Mountains, Telluride, Colorado]", "Bear Creek Falls", "A thin waterfall dropping down a rocky gorge below jagged peaks"),
  photo("ranch.jpg", "32400:32443", "2015632458", "Longhaired highland cattle graze near Ridgway in Ouray County, Colorado", "Highland Ranch", "Two long-haired highland cattle grazing behind a fence with snow-capped mountains beyond"),
  photo("rafting.jpg", "48500:48560", "2017885190", "Rafters on Clear Creek, outside Idaho Falls, Colorado", "Rafting the creek", "Rafts on a fast, rocky creek between steep forested banks"),
  photo("reservoir-path.jpg", "48700:48778", "2017885408", "A cyclist approaches on the bike trail along Dillon Reservoir, outside Frisco, Colorado", "The reservoir path", "A cyclist on a paved path along a reservoir under a dramatic sky"),
  photo("plaza-market.jpg", "33600:33628", "2015633643", "Riders walk their bicycles through Blue River Plaza in downtown Breckenridge, Colorado", "Market day on the plaza", "Cyclists walking their bikes across a plaza where people sit at tables in the sun"),
  photo("balloon-glow.jpg", "37700:37751", "2017687643", "The post-sunset \"glow\" of tethered hot air balloons at the annual Telluride Balloon Festival in the former mining town turned ski resort, but not when the Spring festival is in full swing", "Balloon glow", "A hot-air balloon glowing from inside at dusk above a crowd on the main street"),
  photo("rodeo.jpg", "48800:48852", "2017885482", "Contestant at the Cattlemen's Days rodeo in Gunnison, Colorado", "Rodeo weekend", "A rider on a galloping horse in a rodeo arena, the grandstand behind"),
  photo("snowy-main.jpg", "37100:37132", "2017687290", "Scene on a day when heavy snow covers the main street of Telluride, Colorado", "Main Street in snow", "The main street under heavy snow, brick buildings and parked cars white with it"),
];

const CB = { locality: "Cedar Bend", region: "CO", postal_code: "81499" };
const verified = "2026-09-20";

export const cedarBend: ProofSite = {
  key: "cedar-bend",
  name: "Cedar Bend Guide",
  preset: "community_guide",
  timeZone: "America/Denver",
  contactEmail: "hello@cedarbend.example",
  settings: {
    wordmark: "Cedar Bend Guide",
    tagline: "Shops, trails and the people who keep the town going",
    description: "A guide to Cedar Bend, Colorado: shops, trails, events and the people who keep the town going, checked in person and kept up to date.",
    contact_email: "hello@cedarbend.example",
    contact_phone: "(970) 555-0147",
    contact_address: "PO Box 212\\nCedar Bend, CO 81499",
    primary_color: "#24453a",
    accent_color: "#a04a22",
    background_color: "#f8f5ee",
    text_color: "#23302a",
    typography: "classic-serif",
    logo: "logo.png",
    share_image: "main-street.jpg",
    hero_image: "main-street.jpg",
    home_subheading: "A mountain town of nine hundred people, written up by the ones who live here. Every listing checked in person, no sponsored entries, and an honest note when the hours are unknown.",
    home_intro: "Cedar Bend sits where Bear Creek leaves the canyon and the valley opens out. Main Street is six blocks long, the hot springs are at the end of it, and the trailheads start where the pavement stops.\n\nThis guide is kept by three residents on their own time. It lists the places that are open, the events that are really happening, and the details we could confirm: hours, phone numbers and who to ask. When we could not confirm something, the page says so.",
    about_text: "## Who keeps this guide\n\nThree residents, on their own time: an editor who walks every trail listing twice a year, a photographer who draws the maps sold at the Mercantile, and an events desk that talks to every organizer before a listing goes up.\n\n## How a listing is checked\n\n- Every place carries the date someone from the guide last stood in the doorway.\n- Hours are copied from the door or the owner, never guessed from a category.\n- A cancelled event stays visible with a note so nobody drives out for it.\n- Nothing on these pages is paid for, and no listing can be bought.\n\n## Corrections\n\nIf a detail is wrong, write to us. Corrections go up within a day, and the page shows when it was last checked.",
  },
  artwork: [
    { file: "logo.png", title: "Cedar Bend Guide logo", alt: "Cedar Bend Guide", scene: { type: "logo", lines: ["Cedar Bend", "GUIDE"], fg: "#24453a", accent: "#a04a22", emblem: "peak" } },
    { file: "portrait-nora.png", title: "Nora Vance", alt: "Stylised portrait of Nora Vance, the guide's fictional editor", scene: { type: "portrait", initials: "NV", bg: "#e8dfcf", fg: "#24453a", accent: "#a04a22", seed: 21 } },
    { file: "portrait-eli.png", title: "Eli Marsh", alt: "Stylised portrait of Eli Marsh, the guide's fictional photographer", scene: { type: "portrait", initials: "EM", bg: "#dfe6dc", fg: "#23302a", accent: "#24453a", seed: 22 } },
    { file: "portrait-priya.png", title: "Priya Kaur", alt: "Stylised portrait of Priya Kaur, the guide's fictional events editor", scene: { type: "portrait", initials: "PK", bg: "#f0e3d2", fg: "#24453a", accent: "#a04a22", seed: 23 } },
    { file: "portrait-mateo.png", title: "Mateo Ortiz", alt: "Stylised portrait of Mateo Ortiz, a fictional resident", scene: { type: "portrait", initials: "MO", bg: "#e4e7ea", fg: "#23302a", accent: "#a04a22", seed: 24 } },
    { file: "portrait-dana.png", title: "Dana Whitlock", alt: "Stylised portrait of Dana Whitlock, a fictional shop owner", scene: { type: "portrait", initials: "DW", bg: "#ece2d0", fg: "#24453a", accent: "#23302a", seed: 25 } },
    { file: "mark-trails.png", title: "Cedar Bend Trails Council mark", alt: "Cedar Bend Trails Council", scene: { type: "logo", lines: ["Cedar Bend", "TRAILS COUNCIL"], fg: "#24453a", accent: "#a04a22", emblem: "peak" } },
    { file: "mark-growers.png", title: "Valley Growers mark", alt: "Valley Growers", scene: { type: "logo", lines: ["Valley", "GROWERS"], fg: "#23302a", accent: "#24453a", emblem: "leaf" } },
    { file: "mark-chamber.png", title: "Cedar Bend Chamber mark", alt: "Cedar Bend Chamber of Commerce", scene: { type: "logo", lines: ["Cedar Bend", "CHAMBER"], fg: "#24453a", accent: "#a04a22", emblem: "ring" } },
    { file: "mark-town.png", title: "Town of Cedar Bend mark", alt: "Town of Cedar Bend", scene: { type: "logo", lines: ["Town of", "CEDAR BEND"], fg: "#23302a", accent: "#24453a", emblem: "shield" } },
  ],
  photos,
  rows: {
    place: [
      { external_id: "P-01", title: "Kettle Coffee Cart", category: "Eat & Drink", summary: "A coffee trailer at the trailhead lot, open from half past six: drip, espresso, hot chocolate for the kids and a bench in the sun.", address_line1: "2 Main Street", ...CB, phone: "(970) 555-0101", last_verified_on: verified, ...week("06:30", "14:00"), body: "The cart parks at the trailhead lot at the top of Main Street from half past six, seven days a week, and stays until the beans run out or two o'clock, whichever comes first. Drip is a dollar fifty; espresso drinks are made one at a time, so the line moves at the pace of the person in front of you.\n\nIn winter the window stays open through the snow. There is no seating apart from the bench and the tailgates of the trucks in the lot, which is how everyone likes it.", image: "coffee-cart.jpg" },
      { external_id: "P-02", title: "Hollis Mercantile", category: "Shops", summary: "Groceries, hardware, fuel and the only bear canisters for forty miles. Open early, closes at seven.", address_line1: "101 Main Street", ...CB, phone: "(970) 555-0102", website: "https://hollismercantile.example", last_verified_on: verified, ...week("07:00", "19:00", { sun: "08:00-17:00" }), body: "The Mercantile has been the town's grocery, hardware store and fuel stop since 1911, and it still keeps the post office boxes at the back. The produce comes up from the valley on Tuesdays and Fridays; the hardware aisle can find you a stove part, a fence stretcher or a fishing licence.\n\nThe porch is where notices go: the paper board by the door is the town's classified section, and the guide's editors read it every week.", image: "mercantile.jpg" },
      { external_id: "P-03", title: "Riverstone Books", category: "Shops", summary: "New and used books in the old bank building, with a regional shelf, maps and a reading corner for children.", address_line1: "210 Main Street", ...CB, phone: "(970) 555-0103", website: "https://riverstonebooks.example", last_verified_on: verified, ...week("10:00", "18:00", { mon: "closed", sun: "11:00-16:00" }), body: "Riverstone took over the corner bank building in 2019 and kept the vault, which is now the children's room. The regional shelf holds the trail guides, the mining histories and the county's own oral-history volumes, most of them unavailable anywhere else.\n\nThere are readings on the first Thursday of the month from October to April; the events page lists them once the author is confirmed.", image: "bookshop.jpg" },
      { external_id: "P-04", title: "Spoke & Saddle Bicycles", category: "Outdoors", summary: "Rentals, repairs and route advice from a blue cottage on Aspen Lane; trail bikes, town bikes and a fleet of tag-alongs for children.", address_line1: "14 Aspen Lane", ...CB, phone: "(970) 555-0104", website: "https://spokeandsaddle.example", last_verified_on: verified, ...week("09:00", "18:00", { sun: "closed" }), body: "Rentals go out by the half day, day or week, helmets included, and the mechanic will look at a flat while you wait. The shop keeps a printed map of the reservoir path and the mesa loops, marked with the sections that stay muddy into June.\n\nSunday is the shop's day on the trails, so it is closed; leave a message and they call back Monday morning.", image: "bike-shop.jpg" },
      { external_id: "P-05", title: "Cutbank Anglers", category: "Outdoors", summary: "Flies tied in the back room, guided half days on the creek and honest reports on what is rising.", address_line1: "8 Bridge Street", ...CB, phone: "(970) 555-0105", last_verified_on: verified, ...week("07:00", "18:00"), body: "The shop is a narrow Victorian by the bridge, and the fly bins in the front room are filled from the tying bench behind them. Guided half days run April to October; in winter the shop opens at eight and the guides are mostly tying.\n\nThe daily report on the chalkboard is written from the water, not from the internet, and it says so when nobody has been out.", image: "fly-shop.jpg" },
      { external_id: "P-06", title: "Cedar Bend Hot Springs Pool", category: "Wellness", summary: "The town's outdoor hot springs pool: a warm lap pool, two soaking pools and a slide, open until nine every night.", address_line1: "1200 Main Street", ...CB, phone: "(970) 555-0106", website: "https://cedarbendsprings.example", last_verified_on: verified, ...week("10:00", "21:00"), body: "The pool is fed by the springs at the end of Main Street and kept between 96 and 104 degrees across its sections; the lap pool is the coolest. Towels and suits can be rented at the desk, and lockers take a quarter.\n\nOn summer weekends the slide side fills by noon; the soaking pools on the mountain side stay quieter. The pool closes for cleaning on the second Tuesday of each month.", image: "hot-springs-pool.jpg" },
      { external_id: "P-07", title: "The Sulphur Creek Inn", category: "Stay", summary: "A twelve-room timber inn with its own soaking pool fed by the springs, a block off Main Street.", address_line1: "625 Fifth Avenue", ...CB, phone: "(970) 555-0107", website: "https://sulphurcreekinn.example", last_verified_on: verified, ...week("08:00", "20:00"), body: "The inn's soaking pool is for guests only and open around the clock; the water comes straight from the springs and is changed every night. Rooms are simple, quiet and warm, and breakfast is set out in the lodge room from seven.\n\nThe desk hours listed are when someone answers the phone; guests have their own keys to the front door.", image: "inn-pool.jpg" },
      { external_id: "P-08", title: "Timberline Cabins", category: "Stay", summary: "Six log cabins on the valley road, three miles west of town, with wood stoves and a view of the ridge. Open all year.", area_description: "Three miles west of town on County Road 5, past the ranch gate", ...CB, phone: "(970) 555-0108", last_verified_on: verified, ...week("09:00", "17:00"), body: "The cabins sit on a bench above the valley road with the ridge behind them. Each has a wood stove, a kitchenette and a porch; the firewood is stacked outside the door and included.\n\nThe road is ploughed in winter but a car with good tyres is a good idea after a storm. Booking is by phone during office hours.", image: "cabins.jpg" },
      { external_id: "P-09", title: "Cedar Bend Public Library", category: "Arts & Community", summary: "The 1901 stone library with the clock tower: books, the county archive, free internet and the warmest reading room in town.", address_line1: "320 Sixth Avenue", ...CB, phone: "(970) 555-0109", website: "https://cedarbendlibrary.example", last_verified_on: verified, ...week("10:00", "18:00", { fri: "10:00-15:00", sat: "10:00-15:00", sun: "closed" }), body: "The library keeps the county's newspaper archive back to 1889 on the second floor, and the reading room on the ground floor is open to anyone who wants to sit by the stove. A library card is free to residents and five dollars a year to everyone else.\n\nStory time is Wednesday at ten thirty; the events page lists the talks and film nights.", image: "library.jpg" },
      { external_id: "P-10", title: "Town Park Pavilion", category: "Arts & Community", summary: "The stone pavilion in the park by the creek: picnic tables, a stage for summer concerts and the place the harvest market moves to in the rain.", address_line1: "500 Park Street", ...CB, last_verified_on: verified, ...week("06:00", "22:00"), body: "The pavilion was built in 1934 from creek stone and is the town's outdoor room: picnic tables under the roof, a stage at the far end and the playground beside it. It can be reserved through the town hall for gatherings; otherwise it is open to everyone.\n\nThe park is open from six in the morning until ten at night. Dogs on leads.", image: "park-pavilion.jpg" },
      { external_id: "P-11", title: "Old Mill Museum", category: "Arts & Community", summary: "The 1925 stamp mill on the hillside, kept as it was left, with a guided tour on the hour from May to October.", address_line1: "2 Mill Road", ...CB, phone: "(970) 555-0111", last_verified_on: verified, ...week("10:00", "16:00", { mon: "closed", tue: "closed", wed: "closed" }), body: "The mill processed ore from the ridge mines until 1961 and was left standing with its machinery in place. The volunteer guides, several of whom worked there, take groups through on the hour; the last tour starts at three.\n\nThe museum closes from November to April. The trail past the mill to the upper workings is open all year but not maintained in winter.", image: "mill-museum.jpg" },
      { external_id: "P-12", title: "Depot Visitor Centre", category: "Arts & Community", summary: "The restored 1891 railway depot: maps, trail conditions, the day's weather and someone to ask.", address_line1: "150 Railroad Avenue", ...CB, phone: "(970) 555-0112", last_verified_on: verified, ...week("09:00", "17:00"), body: "The depot is staffed every day by the Chamber's volunteers, who keep the trail-conditions board current and will phone ahead to a cabin or an outfitter for you. The free town map is here, along with the guide's own printed directory.\n\nRestrooms are open when the building is; the platform outside is the best place in town to sit and wait for a ride.", image: "depot.jpg" },
      { external_id: "P-13", title: "Bend Gallery", category: "Shops", summary: "Work by the valley's painters, potters and photographers in the old drug store, with a new show every six weeks.", address_line1: "225 Main Street", ...CB, phone: "(970) 555-0113", website: "https://bendgallery.example", last_verified_on: verified, ...week("11:00", "17:00", { mon: "closed", tue: "closed" }), body: "The gallery is a cooperative of nineteen artists who take turns minding the desk, so the person behind the counter usually made something on the wall. Prices are on the labels and there is no pressure.\n\nOpenings are on the first Friday of the show, with the artists there from five to seven.", image: "gallery.jpg" },
      { external_id: "P-14", title: "Carver's Yard", category: "Shops", summary: "Chainsaw carvings of bears, eagles and the occasional moose, made in the yard on Mill Road and sold from the porch.", address_line1: "40 Mill Road", ...CB, phone: "(970) 555-0114", last_verified_on: verified, ...week("10:00", "17:00", { mon: "closed", tue: "closed", wed: "closed", thu: "closed" }), body: "The carvings are made from beetle-kill spruce brought down from the ridge, and the yard is open when the carver is not up there fetching it: Friday to Sunday, most weeks. Pieces range from a palm-sized bear to a ten-foot totem, and commissions take about a month.\n\nWear closed shoes in the yard; the sawdust hides the offcuts.", image: "carvers-yard.jpg" },
      { external_id: "P-15", title: "Community Church Hall", category: "Arts & Community", summary: "The white church on Chapel Street, whose hall hosts the winter market, the film club and most of the town's potlucks.", address_line1: "12 Chapel Street", ...CB, phone: "(970) 555-0115", last_verified_on: verified, body: "The hall behind the church seats a hundred and has a kitchen, which is why the winter market, the film club and the volunteer fire department's pancake breakfast all happen here. Bookings go through the church office on weekday mornings.\n\nHours are not listed because the hall is opened for events rather than kept open; the events page has the times.", image: "church-hall.jpg" },
      { external_id: "P-16", title: "Bear Creek Falls Trail", category: "Outdoors", summary: "Two and a half miles up the gorge to the falls, steep in places and shaded all day. Allow three hours there and back.", area_description: "Trailhead at the end of Bear Creek Road, a mile and a half south of town", ...CB, last_verified_on: "2026-09-13", body: "The trail follows the creek up the gorge, gaining about 1,200 feet, with two exposed sections that are icy from November to May. The falls are loudest in June; in September the flow is a thin ribbon and the pool at the bottom is warm enough to sit in.\n\nThere is no water on the trail and the lot at the trailhead holds twelve cars. Dogs are fine on a lead. The Trails Council's work days keep the steps in repair; see the events page.", image: "falls-trail.jpg" },
      { external_id: "P-17", title: "Highland Ranch Stays", category: "Stay", summary: "Two guest rooms in a working ranch house four miles north, with highland cattle at the fence and breakfast from the kitchen garden.", area_description: "On the valley road, four miles north of town; the ranch sign is at the cattle guard", ...CB, phone: "(970) 555-0117", website: "https://highlandranchstays.example", last_verified_on: verified, ...week("09:00", "18:00"), body: "The ranch runs sixty head of highland cattle and takes guests in two rooms of the 1920s ranch house. Breakfast comes from the garden and the hen house; dinner can be arranged with a day's notice.\n\nGuests are welcome to walk the fence lines and the creek; calving in April and May closes the lower pasture.", image: "ranch.jpg" },
      { external_id: "P-18", title: "Riverbend Rafting", category: "Outdoors", summary: "Half-day raft trips on the creek's lower canyon from May to September, with a gentle float for families in July and August.", address_line1: "3 Bridge Street", ...CB, phone: "(970) 555-0118", website: "https://riverbendrafting.example", last_verified_on: "2026-09-06", ...week("08:00", "18:00"), body: "Trips leave from the bridge at nine and one, and the water decides which run goes: the canyon when the creek is high, the lower float when it drops in midsummer. Wetsuits and boots are included; bring shoes that can get wet and a change of clothes.\n\nThe office is closed from October to April, so the phone goes to a message; bookings for the coming season open in March.", image: "rafting.jpg" },
      { external_id: "P-19", title: "Reservoir Path", category: "Outdoors", summary: "Seven paved miles around the reservoir, flat enough for children and strollers, with the best view of the peaks from the north shore.", area_description: "Starts at the boat ramp parking lot on Reservoir Road", ...CB, last_verified_on: "2026-09-13", body: "The path is paved all the way round and plowed in winter as far as the dam. Benches every half mile, restrooms at the boat ramp and the north picnic area, and a water tap at the ramp from May to October.\n\nCyclists keep right and call out when passing; the path is shared with walkers, strollers and the occasional deer.", image: "reservoir-path.jpg" },
    ],
    event: [
      { external_id: "E-01", title: "Harvest Market on the Plaza", summary: "Stalls from the valley's growers and bakers on Depot Plaza, music from eleven, and the last tomatoes of the year.", starts_at: "2026-10-03 09:00", ends_at: "2026-10-03 14:00", venue_text: "Depot Plaza, Railroad Avenue", organizer_name: "Valley Growers", admission: "Free", body: "Twenty stalls from the valley: vegetables, fruit, bread, eggs, honey and the Mercantile's coffee. The Growers' own stall sells the market bag for five dollars, and the bag gets you a discount at most stalls.\n\nMoves to the park pavilion in rain. Cash and cards at most stalls.", image: "plaza-market.jpg" },
      { external_id: "E-02", title: "Balloon Glow Night", summary: "Six tethered balloons lit up on the park field at dusk, with the fire department's chili supper from six.", starts_at: "2026-10-10 18:30", ends_at: "2026-10-10 21:00", venue_text: "Town Park field", organizer_name: "Cedar Bend Chamber of Commerce", admission: "Free; chili supper $8", body: "The balloons inflate at half past six and glow on the burners once it is dark, weather permitting; wind over ten knots cancels the glow but not the supper. Bring a chair and a warm coat.\n\nParking is at the school; Park Street closes at six.", image: "balloon-glow.jpg" },
      { external_id: "E-03", title: "Fall Trail Work Morning", summary: "Repairing the steps on the Bear Creek Falls Trail before the snow. Tools, gloves and coffee provided; wear boots.", starts_at: "2026-10-17 08:00", ends_at: "2026-10-17 12:00", venue_text: "Bear Creek Falls trailhead", organizer_name: "Cedar Bend Trails Council", organizer_url: "https://cedarbendtrails.example", admission: "Free", body: "Meet at the trailhead at eight. The council brings tools, gloves and the coffee cart; volunteers bring boots, water and a long-sleeved shirt. Children over twelve are welcome with an adult.\n\nThe work is carrying stone and resetting steps on the two exposed sections; lighter jobs are available.", image: "falls-trail.jpg" },
      { external_id: "E-04", title: "Star Party at the Reservoir", summary: "Telescopes on the north shore for the Orionids, with the astronomy club explaining what you are looking at.", starts_at: "2026-10-16 20:00", ends_at: "2026-10-16 23:00", venue_text: "North picnic area, Reservoir Path", organizer_name: "Valley Astronomy Club", status: "postponed", admission: "Free", body: "Postponed: the club's telescope mount is away for repair and the forecast is cloudy. A new date will be posted here once the mount is back; the listing stays so nobody drives out.", image: "" },
      { external_id: "E-05", title: "Reservoir Ride", summary: "A relaxed lap of the reservoir path for all ages, with a bike check at the boat ramp before the start.", starts_at: "2026-10-25 09:00", ends_at: "2026-10-25 13:00", venue_text: "Boat ramp parking lot, Reservoir Road", organizer_name: "Spoke & Saddle Bicycles", organizer_url: "https://spokeandsaddle.example", admission: "$10, under 16 free", body: "Registration and a free bike check from eight thirty; the ride rolls at nine and takes about two hours at a talking pace. The fee goes to the Trails Council. Rentals are available if booked by the Friday before.", image: "reservoir-path.jpg" },
      { external_id: "E-06", title: "Holiday Lights on Main", summary: "The lighting of Main Street on the Friday after Thanksgiving: carols at the depot, cocoa from the Mercantile and the lights on at six.", starts_at: "2026-11-27 17:00", ends_at: "2026-11-27 20:00", venue_text: "Main Street and Depot Plaza", organizer_name: "Cedar Bend Chamber of Commerce", admission: "Free", body: "Main Street closes to cars at five. The school choir sings at the depot from half past five, the lights come on at six, and the shops stay open until eight. Dress for the cold; the street is at 8,200 feet.", image: "snowy-main.jpg" },
      { external_id: "E-07", title: "Winter Market", summary: "The growers move indoors to the church hall: storage vegetables, preserves, bread, wool and the Christmas trees from the ridge.", starts_at: "2026-12-12 10:00", ends_at: "2026-12-12 15:00", venue_text: "Community Church Hall, 12 Chapel Street", organizer_name: "Valley Growers", admission: "Free", body: "The first of the winter markets, held on the second Saturday of December, January and February in the church hall. Trees are sold from the yard behind the hall while they last.", image: "" },
    ],
    article: [
      { external_id: "A-01", title: "Where the aspens turn first", summary: "The ridge above the mill goes gold a week before the valley. Where to watch it, and when to stop waiting.", author_name: "Eli Marsh", published_on: "2026-09-18", body: "The first colour every year is on the outcrop above the Old Mill, where the aspens stand in shallow soil and give up early. From the mill road you can see it from about the fifteenth of September; by the twenty-fifth the whole ridge has followed.\n\n## Where to stand\n\n- The bench at the mill's upper gate looks straight across at the outcrop.\n- The reservoir path's north shore gives the widest view of the ridge, best in the last hour of light.\n- Bear Creek Road, a mile up from town, is where the valley aspens meet the ridge.\n\n## When it ends\n\nOne good wind takes it all. The valley cottonwoods along the creek turn about ten days after the ridge and hold on into October.", image: "aspens-cliff.jpg" },
      { external_id: "A-02", title: "The valley at dusk", summary: "The mountain wall above town lights up for a few minutes after the sun leaves the valley floor. Three places to watch it from.", author_name: "Cedar Bend Guide", published_on: "2026-09-11", body: "The light on the mountain wall after sunset lasts about eight minutes in September and is gone by the time most people notice it. The trick is to be in place ten minutes before the sun leaves the valley floor.\n\nThe depot platform faces the wall directly and is the easiest. The reservoir path's north shore adds the reflection. The park pavilion is the warmest, with a stove going on market nights.\n\nThe hot springs pool stays open until nine, which is the best seat of all if you do not mind being in the water for it.", image: "alpenglow.jpg" },
      { external_id: "A-03", title: "Elk are back in the lower meadows", summary: "The herd moves through the meadows below town from late September. Where to look, and how not to be the person who gets too close.", author_name: "Nora Vance", published_on: "2026-09-25", body: "The elk come down from the ridge as the nights get cold and spend the mornings in the lower meadows along the creek, usually from the last week of September until the snow pushes them further down the valley.\n\n## Where to look\n\nThe meadows are visible from the reservoir path's south end and from the pull-out on the valley road half a mile past the cabins. Early morning is best; by ten they are back in the trees.\n\n## Keep your distance\n\nA bull in October is not interested in you and will make that clear. Stay on the path, keep dogs on a lead and use the pull-out rather than the road. If the herd changes its behaviour because of you, you are too close.", image: "elk.jpg" },
      { external_id: "A-04", title: "Rodeo weekend, in pictures", summary: "The county's rodeo came through the fairgrounds on the first weekend of August. Eli Marsh was in the stands.", author_name: "Eli Marsh", published_on: "2026-08-02", body: "The county rodeo has been held at the fairgrounds on the first weekend of August for sixty years, and the stands were full for the Saturday performance. The photograph is from the bronc riding; the Sunday programme is the junior events, which are the ones the town really turns out for.\n\nNext year's dates will be on the events page in June, once the county confirms them.", image: "rodeo.jpg" },
      { external_id: "A-05", title: "How this guide checks a listing", summary: "Every place on these pages was visited, and the page says when. Here is what that involves, and what it does not.", author_name: "Cedar Bend Guide", published_on: "2026-09-01", body: "Every listing carries the date someone from the guide last stood in the doorway. That visit checks the hours on the door against the page, the phone number, whether the place is still what it says it is, and whether anything has changed that a visitor would want to know.\n\n## What we do not do\n\nWe do not copy hours from a directory, infer them from the kind of business, or guess. When the bakery has not confirmed its winter Mondays, the listing shows no hours for Monday and says to call ahead.\n\n## What you can do\n\nIf you find a detail wrong, write to us. A correction goes up within a day, and the listing's date is updated when it has been checked again.", image: "downtown.jpg" },
      { external_id: "A-06", title: "Lupine season on the mesa", summary: "The mesa above town turns purple for three weeks in June. Where the best stands are, and why you should stay on the road.", author_name: "Nora Vance", published_on: "2026-06-20", body: "The lupines on the mesa come up in the second week of June and are at their best for about three weeks. The largest stands are along the mesa road a mile past the cattle guard, on the south-facing slope.\n\nThe soil on the mesa is thin and the plants are slow to come back where they are trampled, so the ranch asks walkers to keep to the road and the two marked paths. The view from the road is the best one anyway.", image: "lupines.jpg" },
    ],
  },
};
