/** Starts the Next.js development server and prints useful local entry URLs. */
import { spawn } from "node:child_process";
import { loadEnv } from "./lib/env";

loadEnv();
const port = process.env.PORT ?? "3000";
const base = process.env.APP_URL ?? `http://localhost:${port}`;

console.log(`Lerner Works Platform (local)
  Dashboard:        ${base}/app
  Sign in:          ${base}/sign-in
  Pine Hollow demo: ${base}/demo/pine-hollow
  Range Athletics:  ${base}/demo/range-athletics
  Local accounts:   docs/local-accounts.md (generated by pnpm seed:demo)
`);

const child = spawn("pnpm", ["exec", "next", "dev", "--port", port], { stdio: "inherit", env: process.env });
child.on("exit", (code) => process.exit(code ?? 0));
