/**
 * Loads repeatable, clearly fictional demonstration fixtures into a LOCAL database:
 * two organizations, five local accounts, two demonstration sites. Content fixtures are
 * loaded by the same code path the dashboard's "Load demo content" action uses.
 *
 * Safety: refuses unless APP_ENV=local and the target is a local *_dev/_test/_e2e database.
 * Never destructive: existing records are updated in place; accounts get fresh passwords.
 */
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import postgres from "postgres";
import { assertSafeLocalTarget, loadEnv, projectRoot, requireEnv } from "./lib/env";
import { seedDemo } from "@/server/demo/seed";

loadEnv();

async function main(): Promise<void> {
  const useTest = process.argv.includes("--test");
  const adminUrl = requireEnv(useTest ? "DATABASE_TEST_ADMIN_URL" : "DATABASE_ADMIN_URL");
  const appUrl = requireEnv(useTest ? "DATABASE_TEST_URL" : "DATABASE_URL");
  assertSafeLocalTarget(adminUrl, "Demo seed");
  if (useTest) {
    // Point the application modules at the isolated test database and test storage/mail sinks.
    process.env.DATABASE_URL = appUrl;
    process.env.DATABASE_ADMIN_URL = adminUrl;
    process.env.STORAGE_LOCAL_DIR = process.env.TEST_STORAGE_LOCAL_DIR ?? ".data/test-storage";
    process.env.NOTIFY_LOCAL_DIR = process.env.TEST_NOTIFY_LOCAL_DIR ?? ".data/test-mail";
  }
  const admin = postgres(adminUrl, { max: 1, onnotice: () => {}, transform: postgres.camel });
  try {
    const passwords = new Map<string, string>();
    // Tests pass a fixed password through the environment; ordinary seeds generate one per account.
    const fixed = process.env.SEED_FIXED_PASSWORD;
    const result = await seedDemo(admin, {
      passwordFor: (email) => {
        const p = fixed ?? crypto.randomBytes(12).toString("base64url");
        passwords.set(email, p);
        return p;
      },
      log: (line) => console.log(`  ${line}`),
    });
    const outIndex = process.argv.indexOf("--out");
    if (outIndex !== -1 && process.argv[outIndex + 1]) {
      const outPath = path.resolve(projectRoot, process.argv[outIndex + 1]!);
      fs.mkdirSync(path.dirname(outPath), { recursive: true });
      fs.writeFileSync(outPath, JSON.stringify({ ...result, password: fixed ?? null }, null, 2), { mode: 0o600 });
      console.log(`Seed summary written to ${path.relative(projectRoot, outPath)}`);
    }
    if (!useTest) {
      const accountsPath = path.join(projectRoot, "docs", "local-accounts.md");
      const lines = [
        "# Local demonstration accounts",
        "",
        "Generated by `pnpm seed:demo`. LOCAL ONLY — this file is git-ignored and these accounts must never be created in production.",
        "",
        "| Role | Email | Password |",
        "|---|---|---|",
        ...result.accounts.map((a) => `| ${a.role} | ${a.email} | \`${passwords.get(a.email) ?? "(unchanged)"}\` |`),
        "",
        `Dashboard: ${process.env.APP_URL ?? "http://localhost:3000"}/app`,
        `Pine Hollow demo: ${process.env.APP_URL ?? "http://localhost:3000"}/demo/pine-hollow`,
        `Range Athletics demo: ${process.env.APP_URL ?? "http://localhost:3000"}/demo/range-athletics`,
        "",
      ];
      fs.writeFileSync(accountsPath, lines.join("\n"), { mode: 0o600 });
      console.log(`Accounts written to ${path.relative(projectRoot, accountsPath)} (git-ignored).`);
    }
    console.log("Seed complete.");
  } finally {
    await admin.end();
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.stack ?? err.message : err);
  process.exit(1);
});
